#
###################################
# Site wide configuration
####################################
#
title: Закат
email: cbrwizard@gmail.com
description: Сайт об интерактивной книге Закат
url: http://zakatinteractive.ru
keywords: ["Закат", "Игра", "книга", "интерактивная книга", "choose your own adventure"]

#
###################################
# Jekyll configuration
####################################
#
timezone:          UTC
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: Закат
  avatar: logo.png
  job: "Добро пожаловать в ваш Закат."
  bio: "Интерактивная книга с голосовым режимом на русском языке, дающая читателю как и увлекательную историю с продуманными персонажами, так и право выбирать, как дальше будут развиваться события."
  email: cbrwizard@gmail.com
  disqus-shortname: zakatru
  twitter: zakatru #username
  facebook: zakatinteractive #username
  google:
    plus: #username
    analytics: UA-114510857-1
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: #username
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin:  #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username
  telegram: #username
